import AppKit

/// Watches the system clipboard and hands new content to the store.
///
/// macOS has no "clipboard changed" notification, so every app that does this
/// polls. `NSPasteboard.changeCount` is a counter that increments on every
/// write, so comparing it is cheap — we only actually read data when it moves.
final class ClipboardMonitor {

    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Pasteboard "flavours" that mean "please don't record this".
    /// The `org.nspasteboard.*` ones are a community convention that 1Password,
    /// Bitwarden and friends set when they copy a password.
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        // Created manually (rather than `scheduledTimer`) so we can add it in
        // `.common` mode — that keeps it firing while menus are open.
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func checkForChanges() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.ignoredTypes.contains($0) }) else { return }

        let source = NSWorkspace.shared.frontmostApplication

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // Grab the rich-text flavour too (if any), so "keep formatting"
            // pastes can restore it. Oversized RTF is dropped, not truncated —
            // truncated RTF wouldn't parse.
            var rtf = pasteboard.data(forType: .rtf)
            if let data = rtf, data.count > 262_144 { rtf = nil }
            store.addText(text, rtf: rtf, source: source)
            return
        }

        // Some apps put PNG on the pasteboard, others TIFF. Try both.
        let imageData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
        if let imageData, let image = NSImage(data: imageData) {
            store.addImage(image, source: source)
        }
    }
}
